# Generated by Django 2.0.5 on 2018-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='value',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
